server:
  port: 8083

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc.mysql://localhost:3306/dharma
    username: root
    password: 123456
  jpa:
    hibernate.dll-auto: update
    generate-ddl: true
    show-sql: true

