server:
  port: 8081
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book/**
        - id: infoBook-service
          uri: lb://infoBook-service
          predicates:
            - Path=/author/**
            - Path=/genre/**
            - Path=/store/**
