server:
  port: 8081
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book/**
        - id: info-book-service
          uri: lb://info-book-service
          predicates:
            - Path=/infoBook/author/**, /infoBook/genre/**, /infoBook/store/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: GET, POST, PUT, DELETE
            allowed-headers: "*"
            allow-credentials: true