server:
  port: 8086
spring:
  cloud:
    config:
      server:
        git:
          default-label: client
          uri: https://github.com/Hualmss/dharma-back
          search-paths: config-data
  application:
    name: config-service
