server:
  port: 8082
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dharma
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
